import { AutoGeneratedAxiosClient } from '.';

const appClient = new AutoGeneratedAxiosClient({
  BASE: 'https://api.jikan.moe/v4',
  // CREDENTIALS: 'include',
  // WITH_CREDENTIALS: true,
});

export default appClient;
