import dotenv from 'dotenv';
import { execSync } from 'child_process';

// Load environment variables
// dotenv.config({ path: '../.env' });
// dotenv.config({ path: '../.env.local' });

// const apiHost = process.env.VITE_API_HOST || 'http://localhost';

// if (!apiHost) {
//     console.error("Error: VITE_API_HOST is not defined. Please set it in .env or .env.local or as a runtime environment variable.");
//     process.exit(1);
// }

console.log(`THE LOCATION IS ${process.cwd()}`);

const openapiCommand = `openapi --input anime-api-docs.json -o ./src/api --client axios --name AutoGeneratedAxiosClient --postfixModels Model --useOptions --useUnionTypes --request ./src/api/CustomAxiosRequest.ts`;
execSync(openapiCommand, { stdio: 'inherit', cwd: process.cwd() });

// Run prettier on the generated files
const prettierCommand = `prettier --write ./src/api/**/*.ts`;
execSync(prettierCommand, { stdio: 'inherit' });
